active: mobile_legends
profiles:
  mobile_legends:
    name: Mobile Legends
    package: com.mobile.legends
    landscape: true
    calibrated: false
    buttons:
      attack:
        x: 0.87
        y: 0.75
      skill1:
        x: 0.735
        y: 0.85
      skill2:
        x: 0.775
        y: 0.62
      skill3:
        x: 0.865
        y: 0.45
      ultimate:
        x: 0.865
        y: 0.45
      spell:
        x: 0.66
        y: 0.9
      recall:
        x: 0.6
        y: 0.94
      heal:
        x: 0.955
        y: 0.92
      joystick:
        x: 0.16
        y: 0.72
      minimap:
        x: 0.075
        y: 0.16
      shop:
        x: 0.965
        y: 0.2
      upgrade1:
        x: 0.7
        y: 0.76
      upgrade2:
        x: 0.735
        y: 0.545
      upgrade3:
        x: 0.815
        y: 0.385
  free_fire:
    name: Free Fire
    package: com.dts.freefireth
    landscape: true
    calibrated: false
    buttons:
      tembak:
        x: 0.88
        y: 0.72
      lompat:
        x: 0.93
        y: 0.52
      jongkok:
        x: 0.78
        y: 0.86
      joystick:
        x: 0.15
        y: 0.74
