active: mobile_legends
profiles:
  mobile_legends:
    name: Mobile Legends
    package: com.mobile.legends
    landscape: true
    calibrated: true
    buttons:
      joystick:
        x: 0.182
        y: 0.785
      minimap:
        x: 0.099
        y: 0.134
      attack:
        x: 0.849
        y: 0.858
      burst:
        x: 0.773
        y: 0.691
      aoe:
        x: 0.86
        y: 0.586
      skill1:
        x: 0.773
        y: 0.691
      skill2:
        x: 0.86
        y: 0.586
      recall:
        x: 0.508
        y: 0.892
      regen:
        x: 0.575
        y: 0.892
      flicker:
        x: 0.642
        y: 0.892
      mobility:
        x: 0.723
        y: 0.883
      spell:
        x: 0.642
        y: 0.892
    calib_size: 2280x1080
    catatan: Diukur dari screenshot; verifikasi dengan 'Tes tekan' di tab Game.
  free_fire:
    name: Free Fire
    package: com.dts.freefireth
    landscape: true
    calibrated: false
    buttons:
      tembak:
        x: 0.88
        y: 0.72
      lompat:
        x: 0.93
        y: 0.52
      jongkok:
        x: 0.78
        y: 0.86
      joystick:
        x: 0.15
        y: 0.74
